language: ruby
rvm: 2.5.1
sudo: required
before_install:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get install -y libgsl0-dev
script: bundle exec rake test
env:
  -
  - GSL=t
notifications:
  email:
    on_success: never
    on_failure: change
