dist: bionic
language: ruby
rvm: 2.6
script: bundle exec rake test
addons:
  apt:
    packages:
    - libgsl-dev
env:
  -
  - GSL=t
  - GSL=gslr
notifications:
  email:
    on_success: never
    on_failure: change
