dist: xenial
language: ruby
rvm: 2.6.3
script: bundle exec rake test
addons:
  apt:
    packages:
    - libgsl0-dev
env:
  -
  - GSL=t
  - GSL=gslr
notifications:
  email:
    on_success: never
    on_failure: change
