name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        gemfile: [Gemfile, gemfiles/gsl.gemfile, gemfiles/gslr.gemfile]
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - if: ${{ contains(matrix.gemfile, 'gsl') }}
      run: sudo apt-get install libgsl-dev
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec rake test
